---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-interdomain-nse-composition

resources:
- ../apps/nse-kernel
- ../apps/nsc-kernel
- ns-interdomain-nse-composition.yaml
- netsvc.yaml