---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-interdomain-nse-composition

resources:
- nse-passthrough-1
- nse-passthrough-2
- ns-interdomain-nse-composition.yaml
- client.yaml