---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-interdomain-nse-composition

resources:
- ../apps/nse-kernel
- nse-passthrough-3
- ns-interdomain-nse-composition.yaml